version: '3.3'

services:
  backend:
    build: .
    environment:
      - mongoUrl=mongodb://db:27017/news
      - user=Fampedia
      - password=Fampedia
    volumes:
      - /root/.pm2
    ports:
      - "3000:3000"
    networks: 
      - net
    links:
      - "db:db"
    depends_on:
      - db
    # command: npm start

  db:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    networks: 
      - net
    ports:
      - "27017:27017"
      
networks:
  net: