version: '3.3'

services:
  backend:
    build: .
    environment:
      - mongoUrl=mongodb://db:27017/news
      - NODE_ENV=production
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    restart: always

  db:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
